### PR TITLE
Don't import pygtfs for the version

### PR DESCRIPTION
**Pull request by robbiet480**
Instead of doing `from pygtfs import __version__` I hardcoded the version string because importing pygtfs at this point breaks installing this from another package (https://github.com/balloob/Home-Assistant) because SQLAlchemy is not yet installed.

### CODE REVIEW

**Comment by jarondl** [comment]
Hi @robbiet480.
I don't want to hard-code the version in more than one location, unless **you** promise to keep track of the versions and update them.
We can, however, use another method to read the version string, e.g.:
https://github.com/dateutil/dateutil/blob/master/setup.py#L14
Please modify to another method, and I'll merge.

Yaron

**Comment by jarondl** [comment]
Hi again @robbiet480 or any one else interested in this issue,
You can also use any of the methods described here:
http://python-packaging-user-guide.readthedocs.org/en/latest/single_source_version/

Yaron

**Comment by robbiet480** [comment]
Hey @jarondl sorry I haven't gotten back to this yet, been really busy. It's on my todo list to implement one of the methods on the linked page this weekend and will update the PR with it.

Thanks!

**Comment by jarondl** [comment]
Hi @robbiet480 
Have you started working on this?
I have decided to switch to [setuptools_srm](https://github.com/pypa/setuptools_scm/)
I will implement it myself.

Yaron

**Comment by jarondl** [comment]
Fixed in version 0.1.3

**Pull request closed without merging**
