### PR TITLE
Add location_type

### PR DESCRIPTION
**Pull request by mazzy89**
Signed-off-by: Salvatore Mazzarino <dev@mazzarino.cz> 

This PR should solve the issue #59

### CODE REVIEW

**Comment by mazzy89** [comment]
@jarondl could you give a look here?

**Comment by bdr99** [comment]
According to the [specification](https://developers.google.com/transit/gtfs/reference/), `location_type` can actually be 0, 1, 2, 3, or 4. So perhaps this should be updated to include 4 as well?

**Comment by mazzy89** [comment]
@bdr99 yes. right. that's good call. going to add it.

**Comment by jarondl** [comment]
Thank you for the contribution! Looks good.

**Comment by mazzy89** [comment]
thanks

**Comment by mazzy89** [comment]
@jarondl will you wire a new release?

**Pull request merged**
